config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#new'
  
  get  '/login',         to: 'sessions#new'
  post '/login',         to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'
  
  get  '/signup',        to: 'users#new'
  post '/signup',        to: 'users#create'
  get  '/dashboard',     to: 'users#dashboard'
  
  post '/accept',        to: 'invitations#accept'
  post '/decline',       to: 'invitations#decline'
  
  resources :events
  resources :users,       only: [:new, :create, :show, :destroy]
  resources :invitations, only: [:new, :create]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  
  default_scope { order(datetime: :asc) }
  
  scope :past,   -> { where("datetime <= ?", DateTime.now) }
  scope :future, -> { where("datetime > ?", DateTime.now) }
  
  belongs_to :host, class_name: 'User'
  
  has_many :guests,      through: :invitations
  has_many :invitations, foreign_key: 'attended_event_id', dependent: :destroy
  
  validates :name,         presence: true, uniqueness: true
  validates :location,     presence: true
  validates :datetime,     presence: true
  
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  
  belongs_to :event, foreign_key: 'attended_event_id', dependent: :destroy
  belongs_to :guest, class_name: 'User'
  
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :invitations,     foreign_key: 'guest_id'
  
  has_many :events,          foreign_key: 'host_id',  dependent: :destroy
  has_many :attended_events, through: :invitations, source: :recipient
  
  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  
    # Confirms the correct user is logged in.
    def correct_user?(id)
      user = User.find_by(id: id)
      redirect_to(root_url) unless current_user == user
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  include EventsHelper
  
  before_action only: [:edit, :update, :destroy] do
    correct_user?(Event.find(params[:id]).host.id)
  end
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.new(event_params)
    
    if current_user
      @event.write_attribute(:host_id, current_user.id)
    end
    
    if @event.save
      #adds the host to the event's guest list.
      add_host(current_user, @event)
      redirect_to @event
    else
      flash[:failed] = "Event failed to save!"
      redirect_to new_event_path
    end
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event updated!"
      redirect_to @event
    else
      render 'edit'
    end
  end
  
  def index
    @events = Event.all
  end
  
  def destroy
    Event.find(params[:id]).destroy
    redirect_to dashboard_path
  end
  
  private
  
    def event_params
      params.require(:event).permit(:name, :location, :datetime, :host_id)
    end
  
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  
  include InvitationsHelper
  include EventsHelper
  
  # ensures only the event's host can send invitations.
  before_action only: [:create] do
    correct_user?(event_host)
  end
  
  # and that only the proper guest can accept or decline them.
  before_action only: [:accept, :decline] do
    correct_user?(event_guest)
  end
  
  def new
    @invitation = Invitation.new
  end
  
  def create
    event_id = invitation_params[:attended_event_id]
    guests = invitation_params[:guest_id]
    
    guests.reject! { |g| g.empty? }
    
    invitations = guests.map do |guest_id|
      Invitation.new(attended_event_id: event_id, guest_id: guest_id)
    end
    
    if invitations.any?(&:invalid?)
      flash[:error] = "Failed to save!"
      redirect_to new_invitation_path
    else
      invitations.each(&:save!)
      flash[:success] = "Invitation(s) sent!"
      redirect_to event_path(Event.find(event_id))
    end    
  end
  
  def accept
    event = Event.find(params[:event])
    guest = User.find(params[:guest])
      
    if guest_list(event) && !guest_already_attending?(guest, event)
      Invitation.where(attended_event_id: event.id, guest_id: guest.id).find_each do |inv|
        inv.update_attribute(:accepted, true)
      end
    end
    
    flash[:success] = "Invitation accepted!"
    redirect_to event_path(event)
  end
  
  def decline
    Invitation.where(attended_event_id: params[:event], guest_id: params[:guest]).destroy_all
    
    flash.now[:success] = "Invitation declined!"
    redirect_to dashboard_path
  end
  
  private
  
    def invitation_params
      params.require(:invitation).permit(:attended_event_id, :guest_id => [])
    end
    
    def event_host
      Event.find(params[:invitation][:attended_event_id]).host_id
    end
    
    def event_guest
      User.find(params[:guest])
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(name: params[:session][:name])
    if user
      log_in_as(user)
      redirect_to dashboard_path
    else
      flash.now[:warning] = "Invalid user name!"
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action only: [:destroy] do
    correct_user?(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end
  
  def destroy
    User.find(params[:id]).destroy
  end
  
  def dashboard
    if logged_in?
      @user = current_user
    else
      redirect_to login_url
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  
  #Returns an array of confirmed guests for a given event.
  def guest_list(event)
    guests = event.invitations.where(accepted: true).collect{|inv| inv.guest_id}.uniq || []
    guests.map{|id| User.find_by(id: id)}
  end
  
  #Automatically invites and accepts the host upon creating an event.
  def add_host(host, event)
    Invitation.create(attended_event_id: event.id, guest_id: host.id, accepted: true)
  end
  
end

app/helpers/invitations_helper.rb
module InvitationsHelper
  
  #Checks if a guest has already accepted an invitation to this event.
  def guest_already_attending?(guest, event)
    true if event.invitations.any? do |inv|
      inv.guest_id == guest.id && inv.accepted?
    end
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Returns the current user, if any.
  def current_user
    User.find_by(id: session[:user_id])
  end
  
  # Returns true if a user is logged in.
  def logged_in?
    true if current_user
  end
  
  # Logs in as a specific user.
  def log_in_as(user)
    session[:user_id] = user.id
  end    
  
  # Logs a user out.
  def log_out
    session.delete(:user_id)
    session.delete(:name)
    redirect_to root_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
    
  <div>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
    
  <div>
    <%= f.label :datetime %>
    <%= f.datetime_local_field(:datetime) %>
  </div>
  
  <%= f.submit "#{yield(:submit)}" %>
<% end %>

app/views/events/edit.html.erb
<% provide(:submit, "Update your event!") %>

<h1>Edit an event</h1>

<div>
  <%= render 'form' if @event %>
</div>

app/views/events/index.html.erb
<h1>All Events</h1>

<table>
  <tr>
    <td><strong>Name</strong></td>
    <td><strong>Location</strong></td>
    <td><strong>Date/Time</strong></td>
  </tr>
  <% @events.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.location %></td>
      <td><%= event.datetime %></td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<% provide(:submit, "Launch your event!") %>

<h1>Host an event</h1>

<div>
  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<div>
  <strong><%= @event.location %></strong>
</div>

<p><%= @event.datetime %></p>

<strong>Confirmed Guests:</strong><br />

<ul>
  <% guest_list(@event).each do |g| %>
    <li>
      <%= g.name %>
    </li>
  <% end %>
</ul>

<% if @event.host == current_user %>
  <%= link_to "Invite people to your event!", new_invitation_path(event: {attended_event_id: @event.id}) %>
  <%= link_to "Edit your event.", edit_event_path(@event) %>
  <%= link_to "Cancel your event.", @event, method: :delete %>
<% end %>

app/views/invitations/new.html.erb
<h1>Invite people to your event!</h1>

<%= form_for @invitation do |f| %>

  <div>
    <%= f.label :guests %>
    <%= f.collection_check_boxes :guest_id, User.all, :id, :name %>
  </div>
  
  <%= f.hidden_field :attended_event_id, value: "#{params[:event][:attended_event_id]}" %>
  
  <%= f.submit "Send Invites!" %>
  
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div>
    <% if logged_in? %>
      <% user = current_user %>
      
      <h2><%= user.name %></h2>
      <span><%= link_to "Profile", user %></span>
      <span><%= link_to "Dashboard", dashboard_path %></span>
      <span><%= link_to "All Events", events_path %></span>
      <span><%= link_to "Log out", logout_path, method: :delete %></span>
    <% else %>
      <span><%= link_to "Log in" , login_path,  method: :get %></span>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <h2 style="color:red"><%= content_tag(:div, message) %></h2>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/users/_display_invites.html.erb
<% event = Event.find(event_id) %>
<% host = User.find(event.host_id) %>
          
<td><%= link_to event.name, event_path(event) %></td>
<td>Invited by <%= link_to host.name, user_path(host) %></td>

app/views/users/_event.html.erb
<tr>
  <td><%= link_to event.name, event_path(event) %></td>
  <td><%= event.location %></td>
  <td><%= event.datetime %></td>
</tr>

app/views/users/dashboard.html.erb
<h1>User Dashboard</h1>

<div>
  <h3><%= link_to "Create a new event!", new_event_path %></h3>
</div>


<div>
  <% if @user.events.any? %>
    <div>
      <table>
        <h2>My Past Events</h2>
        <%= render partial: 'event', collection: @user.events.past %>
      </table>
      <table>
        <h2>My Upcoming Events</h2>
        <%= render partial: 'event', collection: @user.events.future %>
      </table>
    </div>
  <% end %>
</div>

<div>
  <% if @user.invitations.any? %>
    <table>
      <h2>Invites Received</h2>
      <% @user.invitations.where(accepted: false).each do |inv| %>
        <tr>
          <%= render partial: 'display_invites', locals: {event_id: inv.attended_event_id} %>
          <td><%= link_to  "Accept",  accept_path(event: inv.event, guest: @user.id), method: :post %></td>
          <td><%= link_to "Decline", decline_path(event: inv.event, guest: @user.id), method: :post %></td>
        </tr>
      <% end %>
      <h2>Events I'm Attending</h2>
      <% @user.invitations.where(accepted: true).each do |inv| %>
        <tr>
          <% event_id = inv.attended_event_id %>
          <%= render partial: 'display_invites', locals: {event_id: event_id} %>
          <% if Event.future.find_by(id: event_id) %>
            <td><%= link_to "Cancel", decline_path(event: event_id, guest: @user.id), method: :post %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div>
  <%= form_for(@user) do |f| %>
  
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.submit 'Create account' %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>
  <%= @user.name %>'s Profile
</h1>